name-template: "v$RESOLVED_VERSION ☕"
tag-template: "v$RESOLVED_VERSION"
autolabeler:
  - label: feature
    branch:
      - "/^feat(ure)?[/-].+/"
  - label: bug
    branch:
      - "/^fix[/-].+/"
  - label: chore
    branch:
      - "/^chore[/-].+/"
  - label: refactor
    branch:
      - "/(refactor|refactoring)[/-].+/"
  - label: documentation
    branch:
      - "/doc(umentation)[/-].+/"
    files:
      - "*.md"
  - label: enhancement
    branch:
      - "/(enh(ancement)|improve)[/-].+/"
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
