#:schema ./schema.json

initial_state = "q0"
accept_states = ["q2"]
blank = "_"
transitions = [
    { from = "q0", to = "q0", read = "0", write = "0", direction = "Right" },
    { from = "q0", to = "q0", read = "1", write = "1", direction = "right" },
    { from = "q0", to = "q0", read = "2", write = "2", direction = "->" },
    { from = "q0", to = "q0", read = "3", write = "3", direction = ">" },
    { from = "q0", to = "q0", read = "4", write = "4", direction = "→" },
    { from = "q0", to = "q0", read = "5", write = "5", direction = "R" },
    { from = "q0", to = "q0", read = "6", write = "6", direction = "r" },
    { from = "q0", to = "q0", read = "7", write = "7", direction = "Right" },
    { from = "q0", to = "q0", read = "8", write = "8", direction = "Right" },
    { from = "q0", to = "q0", read = "9", write = "9", direction = "Right" },
    { from = "q0", to = "q1", read = "_", write = "_", direction = "Left" },

    { from = "q1", to = "q2", read = "_", write = "1", direction = "Left" },
    { from = "q1", to = "q2", read = "0", write = "1", direction = "left" },
    { from = "q1", to = "q2", read = "1", write = "2", direction = "<-" },
    { from = "q1", to = "q2", read = "2", write = "3", direction = "<" },
    { from = "q1", to = "q2", read = "3", write = "4", direction = "←" },
    { from = "q1", to = "q2", read = "4", write = "5", direction = "L" },
    { from = "q1", to = "q2", read = "5", write = "6", direction = "l" },
    { from = "q1", to = "q2", read = "6", write = "7", direction = "Left" },
    { from = "q1", to = "q2", read = "7", write = "8", direction = "Left" },
    { from = "q1", to = "q2", read = "8", write = "9", direction = "Left" },
    { from = "q1", to = "q1", read = "9", write = "0", direction = "Left" },
]
