[target.'cfg(all(target_arch = "x86_64", target_os = "linux"))']
linker = "clang"
rustflags = [
  "-C",
  "link-arg=-fuse-ld=mold",
  "-C",
  "link-args=-target x86_64-unknown-linux-gnu",
]

[target.'cfg(all(target_arch = "aarch64", target_os = "linux"))']
linker = "clang"
rustflags = [
  "-C",
  "link-arg=-fuse-ld=mold",
  "-C",
  "link-args=-target aarch64-unknown-linux-gnu",
]

[target.'cfg(all(target_vendor = "apple", target_os = "macos"))']
linker = "oa64-clang"

[target.x86_64-pc-windows-gnu]
linker = "clang"
rustflags = [
  "-C",
  "link-arg=-fuse-ld=mold",
  "-C",
  "link-args=-target x86_64-pc-windows-gnu",
]

[target.x86_64-pc-windows-msvc]
linker = "lld-link"
rustflags = [
  "-C",
  "linker-flavor=lld-link",
  "-L/.xwin/crt/lib/x86_64",
  "-L/.xwin/sdk/lib/um/x86_64",
  "-L/.xwin/sdk/lib/ucrt/x86_64"
]

[target.aarch64-pc-windows-msvc]
linker = "lld-link"
rustflags = [
  "-C",
  "linker-flavor=lld-link",
  "-L/.xwin/crt/lib/aarch64",
  "-L/.xwin/sdk/lib/um/aarch64",
  "-L/.xwin/sdk/lib/ucrt/aarch64"
]
