[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
  "-C",
  "link-arg=-fuse-ld=mold",
  "-C",
  "link-args=-target x86_64-unknown-linux-gnu",
]

[target.aarch64-unknown-linux-gnu]
linker = "clang"
rustflags = [
  "-C",
  "link-arg=-fuse-ld=mold",
  "-C",
  "link-args=-target aarch64-unknown-linux-gnu",
]

[target.aarch64-apple-darwin]
linker = "oa64-clang"

[target.x86_64-apple-darwin]
linker = "o64-clang"