services:
  tm:
    build:
      context: .
      args:
        MACOS_SDK_URL: ${MACOS_SDK_URL:-}
        MACOS_SDK_FILE_PATH: ${MACOS_SDK_FILE_PATH:-dummy}
        ENABLE_WINDOWS_TARGET: ${ENABLE_WINDOWS_TARGET:-false}
    volumes:
      - ..:/workspace:cacheds
    dns:
      - 1.1.1.1
      - 1.0.0.1
    tty: true
    init: true
