services:
  tm:
    build:
      context: .
      args:
        MACOS_SDK_URL: "${MACOS_SDK_URL:-}"
        MACOS_SDK_FILE_PATH: "${MACOS_SDK_FILE_PATH:-}"
    volumes:
      - ..:/workspace:cacheds
    tty: true
    init: true
