on:
  push:
    paths:
      - "**/*.rs"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - "**/.github/workflows/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        runner:
          - ubuntu-24.04
          - windows-2022
          - macos-13
          - macos-14
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./target/
          key: test-${{ matrix.runner }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: test-${{ matrix.runner }}-

      - name: Run Test
        run: cargo test
    
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.date.outputs.date }}
    steps:
      - id: date
        env: 
          TZ: "Asia/Tokyo"
        run: echo "date=unstable-$(date -u +'%Y%m%d')" >> $GITHUB_OUTPUT

  unstable-build:
    needs: version
    uses: ./.github/workflows/build.yaml
    with:
      version: ${{ needs.version.outputs.version }}
