on:
  push: 
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./target/
          key: test-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: test-

      - name: Setup rust
        run: |
          rustup install nightly
          rustup default nightly

      - name: Run Test
        run: cargo test

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-target:
          - linux
          - macos
          - win-gnu
          - win-msvc
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: ./.github/workflows/build-${{ matrix.build-target }}.yaml
