on:
  push:
    paths:
      - "**/*.rs"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - "**/.github/workflows/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./target/
          key: test-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: test-

      - name: Setup rust
        run: |
          rustup install nightly
          rustup default nightly

      - name: Run Test
        run: cargo test
    
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.date.outputs.date }}
    steps:
      - id: date
        env: 
          TZ: "Asia/Tokyo"
        run: echo "date=unstable-$(date -u +'%Y%m%d')" >> $GITHUB_OUTPUT

  unstable-build:
    needs: version
    uses: ./.github/workflows/build.yaml
    with:
      version: ${{ needs.version.outputs.version }}
