name: Release Drafter

on:
  push:
    tags: 
      - v*

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      
      - name: Check tagged branch
        run: |
          BRANCHS=$(git branch --contains ${{ github.ref_name }})
          set -- $BRANCHS
          for BRANCH in $BRANCHS ; do
            if [[ "$BRANCH" == "main" ]]; then
              exit 0
            fi
          done
          exit 1

      - name: Get version
        id: version
        run: |
          echo "version=${{ github.ref_name }}" >> $GITHUB_OUTPUT

  build:
    uses: ./.github/workflows/build.yaml
    needs:
      - version
    with:
      version: ${{ needs.version.outputs.version }}

  attach-artifacts:
    needs: 
      - version
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: ${{ needs.version.outputs.version }}-*
          merge-multiple: true

      - name: Attach artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
          tag_name: ${{ needs.version.outputs.version }}
          generate_release_notes: true
          draft: true
